# TP4 - Non-negative Matrix Factorization
The goal is to study the use of nonnegative matrix factorisation (NMF) for topic extraction from a dataset of text documents. The rationale is to interpret each extracted NMF component as being associated with a specific topic. 

Study and test the following script (introduced  on [scikit](http://scikit-learn.org/stable/auto_examples/applications/plot_topics_extraction_with_nmf_lda.html))

1. Test and comment on the effect of varying the initialisation, especially using random
nonnegative values as initial guesses (for W and H coefficients, using the notations introduced
during the lecture).
2. Compare and comment on the difference between the results obtained with `2 cost compared
to the generalised Kullback-Liebler cost.
3. Test and comment on the results obtained using a simpler term-frequency representation
as input (as opposed to the TF-IDF representation considered in the code above) when
considering the Kullback-Liebler cost.

In [53]:
###### CUSTOM NMF IMPLEMENTATION ######
# Multiplicative Update Rules for NMF #
# estimation with beta divergences    #
import numpy

# TODO: translate slides 59 [beta-divergence] & 47 [error and special cases]

def custom_NMF(V, K, W=None, H=None, steps=50, beta=0, toll=0.1, show_div=False):
    
    def _beta_div(V,W,H,beta,F,N,K):
        div = 0
        # Update beta_divergence
        if beta == 1: # generalized Kullback-Leibler divergence. x log(x/y) - x + y
            # div = numpy.dot(V, numpy.log(V,numpy.dot(W,H))) - numpy.sum(V) + numpy.sum(numpy.dot(W,H))
            func = _kullback_leiber
        elif beta == 0: # Itakura-Saito divergence. (x/y) - log(x/y) -1
            # div = numpy.sum(V / numpy.dot(W,H)) - numpy.sum(numpy.log(V / numpy.dot(W,H))) - numpy.product(len(V))
            func = _itakura_saito
        else: # Euclidean distance. (1/beta(beta-1))(x^beta + (beta-1)y^beta - beta*x*y^beta-1)
            func = _euclidean_distance
        WH = numpy.dot(W, H)
        for i in range(F):
            for j in range(N):
                x = V[i][j]
                if x == 0:
                    x = numpy.finfo(numpy.double).tiny
                y = WH[i][j]
                div += func(x,y,beta)
        return div

    def _kullback_leiber(x,y,beta):
        return x*numpy.log(x/y) - x + y

    def _itakura_saito(x,y,beta):
        return x*numpy.log(x/y) - x + y

    def _euclidean_distance(x,y,beta):
        return (1/(beta*(beta-1)))*(pow(x,beta) + (beta-1)*pow(y,beta) - beta*x*pow(y,beta-1))

    F = len(V) #Number of V rows
    N = len(V[0]) #Number of V columns

    if W is None:
        W = numpy.random.rand(F,K)
        
    if H is None:
        H = numpy.random.rand(K,N)
        
    if N != len(H[0]):
        raise ValueError("Size for H[0] is different - found "+str(len(H[0]))+" in place of "+str(N))
    if F != len(W):
        raise ValueError("Size for F is different - found "+str(len(F))+" in place of "+str(N))
        
    #Setup n_iter
    n_iter = 1
    
    # Setup initial error
    init_error = _beta_div(V,W,H,beta,F,N,K)
    if show_div:
        print("Initial error: "+str(init_error))
    error = init_error
    
    for step in range(steps):
    
        # Tests with whole matrix : multiply = O | dot = *
        upd_UP = numpy.dot(W.T, numpy.multiply(numpy.power(numpy.dot(W,H),beta-2), V))
        upd_DOWN = numpy.dot(W.T, numpy.power(numpy.dot(W,H),beta-1))
        upd = numpy.divide(upd_UP, upd_DOWN)
        H = numpy.multiply(H, upd)
        
        upd_UP = numpy.dot(numpy.multiply(numpy.power(numpy.dot(W,H),beta-2), V),H.T)
        upd_DOWN = numpy.dot(numpy.power(numpy.dot(W,H),beta-1), H.T)
        upd = numpy.divide(upd_UP, upd_DOWN)
        W = numpy.multiply(W, upd)
        
        # To avoid underflow, we clip H and W to 10^-150
        # so that a multiplication between them is not higher
        # than 10^-307 (smallest exponent on this machime)
        H = numpy.clip(H, 10**-150, None)
        W = numpy.clip(W, 10**-150, None)
        
        if toll > 0:
            new_error = _beta_div(V,W,H,beta,F,N,K)
            if show_div:
                print("Error on iteration "+str(n_iter)+": " +str(new_error))
            # Check if approximation error relative decrease is below the desired threshold
            rel_dec = ((error - new_error) / init_error)
            if show_div:
                print("Error relative decrease at iteration "+str(n_iter)+": "+str(rel_dec))
            if (rel_dec > 0) & (rel_dec < toll):
                break
            error = new_error
            
        n_iter += 1
            
    return W, H



#######

if __name__ == "__main__":
    V = [
         [5,3,0,1],
         [4,0,0,1],
         [1,1,0,5],
         [1,0,0,4],
         [0,1,5,4],
        ]


    V = numpy.array(V) # Data matrix F x N 
    K = 2
    numpy.random.seed(0)
    W, H = custom_NMF(V, K, beta = 0, toll = 0.0001, show_div = True)

Initial error: 34.67244110728304
UPD UP [[26.22816856 21.90221605 15.63381841  7.4459981 ]
 [33.12348114 26.77781457  6.22069807  8.60870146]]
UPD DOWN [[ 5.69757141  7.90335762  8.43496215  2.72573132]
 [ 6.88509565  9.41077583 10.31563582  2.97503389]]
UPD [[4.60339444 2.77125459 1.85345448 2.73174324]
 [4.81089629 2.84544176 0.60303584 2.8936482 ]]
H [[3.64462264 1.46570247 1.05284474 2.52849236]
 [0.34174711 0.24792135 0.01219242 2.40930892]]
W [[0.80920527 0.81040776]
 [0.31568274 0.2344681 ]
 [0.31694595 1.00383222]
 [0.12971685 0.72613382]
 [1.69440161 0.39664803]]
Error on iteration 1: 17.653374180858854
Error relative decrease at iteration 1: 0.4908528613189939
UPD UP [[1.61324507 2.13887294 2.64772886 0.74042672]
 [2.8528978  3.2956275  0.61981554 1.39175054]]
UPD DOWN [[1.16730064 2.64053867 4.63605387 0.9181987 ]
 [2.181817   4.55691273 9.75647966 1.11166384]]
UPD [[1.38203048 0.81001387 0.57111693 0.80639051]
 [1.30757887 0.72321497 0.0635286  1.2519527 ]]
H [[5.03697957e+

In [34]:
##### TEST RESULTS #####
W

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [43]:
import sys
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)